FROM bioconductor/tidyverse:3.21-r-4.5.1
RUN R -e "BiocManager::install('microbiomeMarker')"
COPY .Rprofile /home/rstudio/.Rprofile
# docker build -t registry.cn-hangzhou.aliyuncs.com/wybioinfo/microbiomemarker  .install.packages("microeco")
