FROM registry.cn-hangzhou.aliyuncs.com/wybioinfo/code-server:4.104.3

RUN apt-get update \
	&& DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
		python3 \
		python3-pip \
		python3-venv \
		bash \
	&& rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --no-cache-dir --break-system-packages \
		jupyter \
		jupyterlab \
		bash_kernel \
	&& python3 -m bash_kernel.install --sys-prefix

RUN mkdir -p /config/data /config/extensions \
	&& /app/code-server/bin/code-server \
		--user-data-dir /config/data \
		--extensions-dir /config/extensions \
		--install-extension quarto.quarto



# docker build -t registry.cn-hangzhou.aliyuncs.com/wybioinfo/code-server-quarto .