FROM bioconductor/tidyverse:3.21-r-4.5.1
RUN R -e "BiocManager::install('Maaslin2')"
RUN R -e "install.packages('ggrepel')"
COPY .Rprofile /home/rstudio/.Rprofile
RUN R -e "BiocManager::install('lefser')"
RUN R -e "install.packages('ggpubr')"
# docker build -t registry.cn-hangzhou.aliyuncs.com/wybioinfo/maaslin2:1.22 .