name: Pull Metaphlan and Push to Aliyun ACR

on:
  workflow_dispatch:  # 手动触发

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull staphb/metaphlan:4.1.1
        run: |
          docker pull staphb/metaphlan:4.1.1

      - name: Tag image for Aliyun ACR
        run: |
          docker tag staphb/metaphlan:4.1.1 registry.cn-hangzhou.aliyuncs.com/${{ secrets.ALIYUN_NAMESPACE }}/metaphlan:4.1.1

      - name: Login to Aliyun ACR
        run: |
          echo ${{ secrets.ALIYUN_PASSWORD }} | docker login \
            --username=${{ secrets.ALIYUN_USERNAME }} \
             registry.cn-hangzhou.aliyuncs.com --password-stdin

      - name: Push to Aliyun ACR
        run: |
          docker push registry.cn-hangzhou.aliyuncs.com/${{ secrets.ALIYUN_NAMESPACE }}/metaphlan:4.1.1
